package formulario;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author alexc
 */

import MARSHAL.*;
import jakarta.xml.bind.JAXBContext;
import jakarta.xml.bind.JAXBException;
import jakarta.xml.bind.Marshaller;
import java.io.File;
import java.util.ArrayList;


public class PruebaFormulario extends javax.swing.JDialog {
    
    /**
     * Creates new form PruebaFormulario
     */
    public PruebaFormulario(java.awt.Frame parent, boolean modal) {
        
        initComponents();
        this.setModal(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        personType1 = new javax.swing.JTextField();
        residenceType1 = new javax.swing.JTextField();
        taxIdNumber1 = new javax.swing.JTextField();
        corporateName1 = new javax.swing.JTextField();
        book1 = new javax.swing.JTextField();
        location1 = new javax.swing.JTextField();
        sheet1 = new javax.swing.JTextField();
        folio1 = new javax.swing.JTextField();
        seccion1 = new javax.swing.JTextField();
        volumen1 = new javax.swing.JTextField();
        cp1 = new javax.swing.JTextField();
        ciudad1 = new javax.swing.JTextField();
        provincia1 = new javax.swing.JTextField();
        countryCode1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jDialog1 = new javax.swing.JDialog();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        personType = new javax.swing.JTextField();
        residenceType = new javax.swing.JTextField();
        taxIdNumber = new javax.swing.JTextField();
        corporateName = new javax.swing.JTextField();
        book = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        sheet = new javax.swing.JTextField();
        folio = new javax.swing.JTextField();
        seccion = new javax.swing.JTextField();
        volumen = new javax.swing.JTextField();
        cp = new javax.swing.JTextField();
        ciudad = new javax.swing.JTextField();
        provincia = new javax.swing.JTextField();
        countryCode = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel17.setText("Formulario de prueba uwu");

        jLabel18.setText("Person type code");

        jLabel19.setText("Residence type code");

        jLabel20.setText("Tax identification number");

        jLabel21.setText("Corporate Name");

        jLabel22.setText("Book");

        jLabel23.setText("Location");

        jLabel24.setText("Sheet");

        jLabel25.setText("Folio");

        jLabel26.setText("Section");

        jLabel27.setText("Volumen");

        jLabel28.setText("Address");

        jLabel29.setText("CP");

        jLabel30.setText("Town");

        jLabel31.setText("Province");

        jLabel32.setText("Country Code");

        personType1.setText("J");

        residenceType1.setText("R");

        taxIdNumber1.setText("Q0000000J");

        corporateName1.setText("nESTOR sORIANO");

        book1.setText("0");

        location1.setText("Registro de uwus");

        sheet1.setText("999999");

        folio1.setText("99");
        folio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folio1ActionPerformed(evt);
            }
        });

        seccion1.setText("9");
        seccion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccion1ActionPerformed(evt);
            }
        });

        volumen1.setText("9999");
        volumen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumen1ActionPerformed(evt);
            }
        });

        cp1.setText("calle falsa 123");
        cp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cp1ActionPerformed(evt);
            }
        });

        ciudad1.setText("07600");
        ciudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudad1ActionPerformed(evt);
            }
        });

        provincia1.setText("jTextField2");
        provincia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provincia1ActionPerformed(evt);
            }
        });

        countryCode1.setText("ESP");
        countryCode1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryCode1ActionPerformed(evt);
            }
        });

        jButton2.setText("ENVIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(41, 41, 41))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(personType1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(residenceType1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taxIdNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(corporateName1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sheet1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(folio1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seccion1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(volumen1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(countryCode1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cp1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(provincia1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(179, 179, 179))))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(4, 4, 4)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(countryCode1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(personType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(residenceType1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(taxIdNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(corporateName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(book1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(location1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(sheet1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(folio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25))
                .addGap(31, 31, 31)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(seccion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(volumen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(cp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(ciudad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(provincia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 502, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Formulario de prueba uwu");

        jLabel2.setText("Person type code");

        jLabel3.setText("Residence type code");

        jLabel4.setText("Tax identification number");

        jLabel5.setText("Corporate Name");

        jLabel6.setText("Book");

        jLabel7.setText("Location");

        jLabel8.setText("Sheet");

        jLabel9.setText("Folio");

        jLabel10.setText("Section");

        jLabel11.setText("Volumen");

        jLabel12.setText("Address");

        jLabel13.setText("CP");

        jLabel14.setText("Town");

        jLabel15.setText("Province");

        jLabel16.setText("Country Code");

        personType.setText("J");

        residenceType.setText("R");

        taxIdNumber.setText("Q0000000J");

        corporateName.setText("nESTOR sORIANO");

        book.setText("0");

        location.setText("Registro de uwus");

        sheet.setText("999999");

        folio.setText("99");
        folio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                folioActionPerformed(evt);
            }
        });

        seccion.setText("9");
        seccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seccionActionPerformed(evt);
            }
        });

        volumen.setText("9999");
        volumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumenActionPerformed(evt);
            }
        });

        cp.setText("calle falsa 123");
        cp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpActionPerformed(evt);
            }
        });

        ciudad.setText("07600");
        ciudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ciudadActionPerformed(evt);
            }
        });

        provincia.setText("jTextField2");
        provincia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                provinciaActionPerformed(evt);
            }
        });

        countryCode.setText("ESP");
        countryCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryCodeActionPerformed(evt);
            }
        });

        jButton1.setText("ENVIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(countryCode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addComponent(personType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(residenceType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel4)
                .addGap(43, 43, 43)
                .addComponent(taxIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(corporateName, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(sheet, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(289, 289, 289)
                .addComponent(jButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel16))
                    .addComponent(countryCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addComponent(personType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addComponent(residenceType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(taxIdNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(corporateName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(book, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(sheet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(folio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addComponent(seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel11))
                    .addComponent(volumen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel12))
                    .addComponent(cp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel13))
                    .addComponent(ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel14))
                    .addComponent(provincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jButton1))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void folioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folioActionPerformed

    private void seccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seccionActionPerformed

    private void volumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumenActionPerformed

    private void cpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpActionPerformed

    private void ciudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudadActionPerformed

    private void provinciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provinciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provinciaActionPerformed

    private void countryCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryCodeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       procesarFormulario();
       dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void folio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_folio1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_folio1ActionPerformed

    private void seccion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seccion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seccion1ActionPerformed

    private void volumen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volumen1ActionPerformed

    private void cp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cp1ActionPerformed

    private void ciudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ciudad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ciudad1ActionPerformed

    private void provincia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_provincia1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_provincia1ActionPerformed

    private void countryCode1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryCode1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryCode1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField book;
    private javax.swing.JTextField book1;
    private javax.swing.JTextField ciudad;
    private javax.swing.JTextField ciudad1;
    private javax.swing.JTextField corporateName;
    private javax.swing.JTextField corporateName1;
    private javax.swing.JTextField countryCode;
    private javax.swing.JTextField countryCode1;
    private javax.swing.JTextField cp;
    private javax.swing.JTextField cp1;
    private javax.swing.JTextField folio;
    private javax.swing.JTextField folio1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField location;
    private javax.swing.JTextField location1;
    private javax.swing.JTextField personType;
    private javax.swing.JTextField personType1;
    private javax.swing.JTextField provincia;
    private javax.swing.JTextField provincia1;
    private javax.swing.JTextField residenceType;
    private javax.swing.JTextField residenceType1;
    private javax.swing.JTextField seccion;
    private javax.swing.JTextField seccion1;
    private javax.swing.JTextField sheet;
    private javax.swing.JTextField sheet1;
    private javax.swing.JTextField taxIdNumber;
    private javax.swing.JTextField taxIdNumber1;
    private javax.swing.JTextField volumen;
    private javax.swing.JTextField volumen1;
    // End of variables declaration//GEN-END:variables
    
    // Handlers aqui
    // Por cada pestaña del formulario

// Método que el botón final llama
private void procesarFormulario() {
    SellerPartyHandler sellerPartyHandler = new SellerPartyHandler(book, ciudad, corporateName, countryCode, cp, folio, personType, taxIdNumber, sheet, location, seccion, volumen);

    try {
    // Crear la factura
            Facturae facturae = new Facturae();

            // Configuración del FileHeader
            FileHeader fileHeader = new FileHeader();
            fileHeader.setSchemaVersion("3.2.2");
            fileHeader.setModality("I");
            fileHeader.setInvoiceIssuerType("EM");

            // Configuración del Batch
            Batch batch = new Batch();
            batch.setBatchIdentifier("A80907397SMP008166239");
            batch.setInvoicesCount(1);

            TotalAmount totalInvoicesAmount = new TotalAmount();
            totalInvoicesAmount.setTotalAmount(2420.00);
            batch.setTotalInvoicesAmount(totalInvoicesAmount);

            TotalAmount totalOutstandingAmount = new TotalAmount();
            totalOutstandingAmount.setTotalAmount(2420.00);
            batch.setTotalOutstandingAmount(totalOutstandingAmount);

            TotalAmount totalExecutableAmount = new TotalAmount();
            totalExecutableAmount.setTotalAmount(2420.00);
            batch.setTotalExecutableAmount(totalExecutableAmount);

            batch.setInvoiceCurrencyCode("EUR");
            fileHeader.setBatch(batch);
            facturae.setFileHeader(fileHeader);

            // Configuración de las Parties
            Parties parties = new Parties();

            // SellerParty
           
            SellerParty sellerParty = sellerPartyHandler.getSellerParty();
            parties.setSellerParty(sellerParty);
            // BuyerParty
            BuyerParty buyerParty = new BuyerParty();
            TaxIdentification buyerTaxId = new TaxIdentification();
            buyerTaxId.setPersonTypeCode("J");
            buyerTaxId.setResidenceTypeCode("R");
            buyerTaxId.setTaxIdentificationNumber("B00000000");
            buyerParty.setTaxIdentification(buyerTaxId);
            buyerParty.setPartyIdentification("99999999");

            // AdministrativeCentres

 





            LegalEntity buyerLegalEntity = new LegalEntity();
            buyerLegalEntity.setCorporateName("CIFP FBmoll 2DAM");

            buyerParty.setLegalEntity(buyerLegalEntity);

            parties.setBuyerParty(buyerParty);
            facturae.setParties(parties);

            // Configuración de las Invoices
            Invoices invoices = new Invoices();
            Invoice invoice = new Invoice();

            InvoiceHeader invoiceHeader = new InvoiceHeader();
            invoiceHeader.setInvoiceNumber("19870617");
            invoiceHeader.setInvoiceDocumentType("FC");
            invoiceHeader.setInvoiceClass("OO");
            invoice.setInvoiceHeader(invoiceHeader);

            // InvoiceIssueData
            InvoiceIssueData invoiceIssueData = new InvoiceIssueData();
            invoiceIssueData.setIssueDate("2022-06-05");
            invoiceIssueData.setInvoiceCurrencyCode("EUR");
            invoiceIssueData.setTaxCurrencyCode("EUR");
            invoiceIssueData.setLanguageName("es");
            
            invoiceIssueData.setInvoiceDescription("Esto es una factura de prueba, uwu.");
            
            
            invoice.setInvoiceIssueData(invoiceIssueData);

            // TaxesOutputs
            TaxesOutputs taxesOutputs = new TaxesOutputs();
            Tax tax = new Tax();
            tax.setTaxTypeCode("01");
            tax.setTaxRate(21.00);
            TaxableBase taxableBase = new TaxableBase();
            taxableBase.setTotalAmount(2000.00);
            tax.setTaxableBase(taxableBase);

            TaxAmount taxAmount = new TaxAmount();
            taxAmount.setTotalAmount(420.00);
            tax.setTaxAmount(taxAmount);

            // Inicializa la lista antes de añadir
            if (taxesOutputs.getTax() == null) {
                taxesOutputs.setTax(new ArrayList<>());
            }
            taxesOutputs.getTax().add(tax);
           
            // InvoiceTotals
            invoice.setTaxesOutputs(taxesOutputs);
            InvoiceTotals invoiceTotals = new InvoiceTotals();
            
            
            invoiceTotals.setTotalGrossAmount("2420.00"); // Total bruto
            invoiceTotals.setTotalGrossAmountBeforeTaxes("2000.00"); // Total bruto antes de impuestos
            invoiceTotals.setTotalTaxOutputs("420.00"); // Total de impuestos
            invoiceTotals.setInvoiceTotal("2000.00"); // Establecer el valor correspondiente
            invoiceTotals.setTotalOutstandingAmount("2420.00"); // Total a pagar
            invoiceTotals.setTotalTaxesWithheld("50");
            invoiceTotals.setTotalExecutableAmount(2420.00); // Total ejecutable
            invoice.setInvoiceTotals(invoiceTotals);

            // Items
            Items items = new Items();

            // Primer ítem
            InvoiceLine invoiceLine1 = new InvoiceLine();
            invoiceLine1.setIssuerContractReference("123456789");
            invoiceLine1.setFileReference("NUMREFxx");
            invoiceLine1.setItemDescription("Ensaimada gigantesca");
            invoiceLine1.setQuantity(1);
            invoiceLine1.setUnitPriceWithoutTax(2000.00); // Precio unitario sin impuestos
            invoiceLine1.setTotalCost(2000.00); // Costo total
            invoiceLine1.setGrossAmount(2420.00); // Monto bruto
            invoiceLine1.setTaxesOutputs(taxesOutputs); // Usar la variable de taxesOutputs

            LineItemPeriod lineItemPeriod1 = new LineItemPeriod();
            lineItemPeriod1.setStartDate("2022-06-05");
            lineItemPeriod1.setEndDate("2023-06-05");
            invoiceLine1.setLineItemPeriod(lineItemPeriod1);

            // Inicializa la lista antes de añadir
            if (items.getInvoiceLine() == null) {
                items.setInvoiceLine(new ArrayList<>());
            }
            items.getInvoiceLine().add(invoiceLine1);

            // Segundo ítem
            InvoiceLine invoiceLine2 = new InvoiceLine();
            invoiceLine2.setIssuerContractReference("987654321");
            invoiceLine2.setFileReference("NUMREFyy");
            invoiceLine2.setItemDescription("Chocolate con churros");
            invoiceLine2.setQuantity(1);
            invoiceLine2.setUnitPriceWithoutTax(500.00); // Precio unitario sin impuestos
            invoiceLine2.setTotalCost(500.00); // Costo total
            invoiceLine2.setGrossAmount(605.00); // Monto bruto
            invoiceLine2.setTaxesOutputs(taxesOutputs); // Usar la variable de taxesOutputs

            LineItemPeriod lineItemPeriod2 = new LineItemPeriod();
            lineItemPeriod2.setStartDate("2022-06-05");
            lineItemPeriod2.setEndDate("2023-06-05");
            invoiceLine2.setLineItemPeriod(lineItemPeriod2);

            // Añadir el segundo ítem a la lista
            items.getInvoiceLine().add(invoiceLine2);

            // Asignar items a la factura
            invoice.setItems(items);


            // PaymentDetails
            PaymentDetails paymentDetails = new PaymentDetails();

            // Crear objeto Installment
            Installment installment = new Installment();
            installment.setInstallmentDueDate("2022-06-05");
            installment.setInstallmentAmount("2420.00"); // Asegúrate de que sea un String con dos decimales
            installment.setPaymentMeans("04"); // Usa el código de pago como String

            // Crear objeto AccountToBeCredited
            AccountToBeCredited accountToBeCredited = new AccountToBeCredited();
            accountToBeCredited.setIban("ES1000491500022910080785");
            installment.setAccountToBeCredited(accountToBeCredited);

            // Añadir el installment al PaymentDetails
            if (paymentDetails.getInstallments() == null) {
                paymentDetails.setInstallments(new ArrayList<>());
            }
            paymentDetails.getInstallments().add(installment);

            // Inicializa la lista de installments antes de añadir
            if (paymentDetails.getInstallments() == null) {
                paymentDetails.setInstallments(new ArrayList<>());
            }
            paymentDetails.getInstallments().add(installment);
            invoice.setPaymentDetails(paymentDetails);

            // AdditionalData
            AdditionalData additionalData = new AdditionalData();
            additionalData.setInvoiceAdditionalInformation("Nerf BBKarin");
            invoice.setAdditionalData(additionalData);

            // Añadir la factura a la lista de Invoices
            if (invoices.getInvoice() == null) {
                invoices.setInvoice(new ArrayList<>());
            }
            invoices.getInvoice().add(invoice);
            facturae.setInvoices(invoices);

            // Marshalling
            JAXBContext context = JAXBContext.newInstance(Facturae.class);
            Marshaller marshaller = context.createMarshaller();
            marshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
            marshaller.marshal(facturae, new File("facturasinACentres.xml"));


            } catch (JAXBException e) {
                e.printStackTrace();
            }
      
}







}
